[package]
name = "fisherman"
version = "0.1.0"
authors = ["Alexander Jackson <alexanderjackson@protonmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
warp = "0.2"
log = "0.4"
chrono = "0.4"
git2 = "0.13"

[dependencies.tokio]
version = "0.2"
features = ["macros"]

[dependencies.serde]
version = "1"
features = ["derive"]

[dependencies.fern]
version = "0.5"
features = ["colored"]
